defmodule ControlKeel.Cloud.AuthToken do
  @moduledoc """
  Short-lived ed25519-signed Bearer tokens for cloud telemetry requests.

  Replaces the placeholder Bearer-workspace_id from earlier slices. Implements
  the runtime-authz half of architectural decision D2: the workspace keypair
  generated by `controlkeel cloud connect` signs a small claims payload, and
  the receiver verifies against the registered public key.

  ## Token format

      <base64url(payload_json)>.<base64url(signature)>

  Payload JSON shape:

      {
        "ws":  "ws_abc...",
        "iat": 1716494400,
        "exp": 1716494700,
        "nonce": "<8 random bytes hex>"
      }

  ## TTL

  Default 5 minutes. Short enough that we don't need a replay-protection nonce
  cache for the initial self-host loop. A future slice can add server-side
  nonce caching when multi-tenant cloud lands.

  ## Verification

  Verification resolves the workspace public key in two steps (architectural
  decision D8 in [cloud-enterprise-roadmap.md](../../docs/cloud-enterprise-roadmap.md)):

    1. `KeyRegistry.fetch/1` — the multi-tenant registry table.
       This is what controlkeel.com uses to verify Bearer tokens posted by
       enrolled laptops.
    2. Falls back to `Identity.load/0` for single-node self-host
       deployments where the sender and receiver are the same process.

  On a successful verify the registry's `last_seen_at` is touched so the
  org-scoped projects UI can show fresh-vs-stale workspaces.
  """

  alias ControlKeel.Cloud.Workspace.Identity
  alias ControlKeel.Cloud.Workspace.KeyRegistry

  @default_ttl_seconds 300
  @signature_size_bytes 64

  @typedoc "Verified claims."
  @type claims :: %{
          workspace_id: String.t(),
          issued_at: DateTime.t(),
          expires_at: DateTime.t()
        }

  @typedoc "Verification failures."
  @type verify_error ::
          :missing_token
          | :malformed
          | :bad_signature
          | :expired
          | :unknown_workspace
          | :public_key_invalid

  @doc """
  Sign a Bearer token using the given local identity.

  Returns `{:ok, token}` on success.
  """
  @spec sign(Identity.t(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def sign(%{workspace_id: ws, private_key: priv_b64} = _identity, opts \\ []) do
    ttl = Keyword.get(opts, :ttl_seconds, @default_ttl_seconds)
    now = DateTime.utc_now() |> DateTime.truncate(:second)
    exp = DateTime.add(now, ttl, :second)

    payload = %{
      "ws" => ws,
      "iat" => DateTime.to_unix(now),
      "exp" => DateTime.to_unix(exp),
      "nonce" => :crypto.strong_rand_bytes(8) |> Base.encode16(case: :lower)
    }

    with {:ok, priv} <- Base.decode64(priv_b64),
         payload_json = Jason.encode!(payload),
         signature = :crypto.sign(:eddsa, :sha512, payload_json, [priv, :ed25519]) do
      token =
        Base.url_encode64(payload_json, padding: false) <>
          "." <> Base.url_encode64(signature, padding: false)

      {:ok, token}
    else
      :error -> {:error, :public_key_invalid}
      other -> {:error, other}
    end
  end

  @doc """
  Verify a Bearer token.

  Returns `{:ok, claims}` when signature is valid, the token has not expired,
  and the named workspace's public key is locally resolvable.
  """
  @spec verify(String.t() | nil) :: {:ok, claims()} | {:error, verify_error()}
  def verify(nil), do: {:error, :missing_token}
  def verify(""), do: {:error, :missing_token}

  def verify(token) when is_binary(token) do
    with {:ok, payload_json, signature} <- split_token(token),
         {:ok, payload} <- decode_payload(payload_json),
         {:ok, ws_id, iat, exp} <- extract_claims(payload),
         {:ok, pub_key, source} <- resolve_public_key(ws_id),
         :ok <- verify_signature(payload_json, signature, pub_key),
         :ok <- verify_not_expired(exp) do
      if source == :registry, do: KeyRegistry.touch_last_seen(ws_id)

      {:ok,
       %{
         workspace_id: ws_id,
         issued_at: DateTime.from_unix!(iat),
         expires_at: DateTime.from_unix!(exp)
       }}
    else
      {:error, reason} when is_atom(reason) -> {:error, reason}
      {:error, _other} -> {:error, :malformed}
      _ -> {:error, :malformed}
    end
  catch
    _, _ -> {:error, :malformed}
  end

  defp decode_payload(json) do
    case Jason.decode(json) do
      {:ok, map} -> {:ok, map}
      {:error, _} -> {:error, :malformed}
    end
  end

  defp split_token(token) do
    case String.split(token, ".", parts: 2) do
      [payload_b64, sig_b64] ->
        with {:ok, payload_json} <- url_decode(payload_b64),
             {:ok, signature} <- url_decode(sig_b64),
             true <- byte_size(signature) == @signature_size_bytes do
          {:ok, payload_json, signature}
        else
          _ -> {:error, :malformed}
        end

      _ ->
        {:error, :malformed}
    end
  end

  defp url_decode(value) do
    case Base.url_decode64(value, padding: false) do
      {:ok, decoded} -> {:ok, decoded}
      :error -> {:error, :malformed}
    end
  end

  defp extract_claims(%{"ws" => ws, "iat" => iat, "exp" => exp})
       when is_binary(ws) and is_integer(iat) and is_integer(exp) do
    {:ok, ws, iat, exp}
  end

  defp extract_claims(_), do: {:error, :malformed}

  defp resolve_public_key(workspace_id) do
    case KeyRegistry.fetch(workspace_id) do
      {:ok, %{public_key: pub_b64}} ->
        case Base.decode64(pub_b64) do
          {:ok, pub} -> {:ok, pub, :registry}
          :error -> {:error, :public_key_invalid}
        end

      {:error, :not_found} ->
        resolve_from_local_identity(workspace_id)
    end
  rescue
    # Registry table may not exist in some test repos or older self-host
    # builds. Fall back to the local identity in that case.
    _ -> resolve_from_local_identity(workspace_id)
  end

  defp resolve_from_local_identity(workspace_id) do
    case Identity.load() do
      {:ok, %{workspace_id: ^workspace_id, public_key: pub_b64}} ->
        case Base.decode64(pub_b64) do
          {:ok, pub} -> {:ok, pub, :local}
          :error -> {:error, :public_key_invalid}
        end

      {:ok, _other_identity} ->
        {:error, :unknown_workspace}

      {:error, _} ->
        {:error, :unknown_workspace}
    end
  end

  defp verify_signature(payload_json, signature, pub_key) do
    if :crypto.verify(:eddsa, :sha512, payload_json, signature, [pub_key, :ed25519]) do
      :ok
    else
      {:error, :bad_signature}
    end
  rescue
    _ -> {:error, :bad_signature}
  end

  defp verify_not_expired(exp_unix) do
    if DateTime.to_unix(DateTime.utc_now()) < exp_unix do
      :ok
    else
      {:error, :expired}
    end
  end
end
