defmodule ControlKeel.Repo.Migrations.AddExternalIdToCloudRunPackages do
  use Ecto.Migration

  def up do
    alter table(:cloud_run_packages) do
      add :external_id, :string
    end

    # Backfill any pre-existing rows with a stable legacy id so the unique
    # index can be applied. New rows generated by RuntimeContext use a real
    # pkg_<ulid> at insert.
    execute("""
    UPDATE cloud_run_packages
       SET external_id = 'pkg_legacy_' || id
     WHERE external_id IS NULL
    """)

    create unique_index(:cloud_run_packages, [:external_id])
  end

  def down do
    drop index(:cloud_run_packages, [:external_id])

    alter table(:cloud_run_packages) do
      remove :external_id
    end
  end
end
