defmodule ControlKeel.Repo.Migrations.AddExternalIdToTasks do
  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :external_id, :string
    end

    # Backfill existing rows with a stable legacy id so the unique index
    # can be applied. New rows generated by Mission.create_task/1 use a
    # real task_<ulid>.
    execute("""
    UPDATE tasks
       SET external_id = 'task_legacy_' || id
     WHERE external_id IS NULL
    """)

    create unique_index(:tasks, [:external_id])
  end

  def down do
    drop index(:tasks, [:external_id])

    alter table(:tasks) do
      remove :external_id
    end
  end
end
